apiVersion: v1
kind: Service
metadata:
  name: homecoach-prometheus-exporter
  labels:
    app: homecoach-prometheus-exporter
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      name: http
  selector:
    app: homecoach-prometheus-exporter
